source 'https://rubygems.org'

gem 'jekyll', '3.8.5'

gem "github-pages", "~> 202", group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "wdm", "~> 0.1.0" if Gem.win_platform?